<html>

<head>
    <style>
        .sub {
            display: flex;
            color: black;
            text-align: -webkit-center;
            place-content: space-between;
            justify-content: center;
            border-top: 2px solid black;
            padding-top: 10px;
            padding-bottom: 10px;
            width: 90%;
            margin-left: 5%;
            margin-right: 5%;
            height: fit-content;
            border-bottom: 2px solid black;
        }

        .half-div1 {
            width: 50%;
            display: inline-block;
            vertical-align: top;
        }

        .half-div2 {

            width: 50%;
            border-left: 2px solid black;
            display: inline-block;
            vertical-align: top;
        }


        h5,
        h6,
        h4 {
            margin: 0;
        }

        h5{
            text-align: center;

            font-size: 15px;
        }
        h6 {
            margin: 5px;
        }

        .row {
            display: flex;
            justify-content: space-between;
            border-bottom: 1px solid #ccc;
            padding: 8px 0;
        }

        .header {
            font-weight: bold;
        }




        .customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 90%;
            margin-left: 5%;
            margin-right: 5%;
            padding-bottom: 15px;

        }

        .customers td,
        .customers th {
            border: 1.5px solid black;
            font-size: 16px;
            padding: 8px;
        }




        .tmain {
            background-color: white;
            margin: 10px;

            padding: 2px;
            border-radius: 25px;
        }
.normal_text{
    font-weight: 500;
}
        .hmain {
            color: white;
            font-size: 25px;
            margin-top: -20px;
        }

        h4,
        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }
    </style>
</head>
 

<body style="background-color:{{ session()->get('primary_color')[0] }}; border-radius: 25px;">



    <div class="hmain">

        <h3 style="font-size:40px;">Site Bill</h3>

    </div>

    <div class="tmain">
        <h3 style="font-size:30px;">{{ $bill_party->name }}</h3>
        <h4 style="font-size:15px;margin-top:-25px; text-wrap:wrap; ">@if($bill_party->address != null && $bill_party->address != "" )Address: {{$bill_party->address}}</h4>@endif
        <p style="font-size:15px;">Pan No. : {{$bill_party->panno}}</p>


        <table class="customers">

            <tr>
                <td style="width:50%; text-align:center;">
                    <h5>Site : <span class="normal_text">{{ $bill->site }} </span></h5>
                    <h5>Generated By : <span class="normal_text">{{ $bill->user }} </span></h5>
                </td>
                <td style="width:50%; text-align:center;">
                    <h5>Bill No. : <span class="normal_text">{{ $bill->bill_no }}</span></h5>
                    <h5>Bill Date : <span class="normal_text">{{ $bill->billdate }}</span></h5>
                    <h5>Bill Period : <span class="normal_text">{{ $bill->bill_period }}</span></h5>
                </td>
            </tr>
        </table>
        <table class="customers">
        <tr><th>#</th><th>Item</th><th>Quantity</th><th>Unit</th><th>Unit Cost</th><th>Total</th></tr>
        @php
        $count = 1;
    @endphp
    @foreach ($bill_items as $bill_item)
        @php
            $amount = $bill_item->rate * $bill_item->qty;
        @endphp
        <tr>
            <td><h5>{{ $count++ }}</h5></td>
            <td><h5>{{ $bill_item->name }}</h5></td>
            <td><h5>{{ $bill_item->qty }}</h5></td>
            <td><h5>{{ $bill_item->unit }}</h5></td>
            <td class="hidden-sm-down">
                <h5>{{ getStructuredAmount($bill_item->rate, false, false) }}</h5>
            </td>
            <td><h5>{{ getStructuredAmount($amount, false, false) }}</h5></td>
        </tr>
    @endforeach

        </table>
        
        <table class="customers">
     
            <tr >
                <td style="width:25%;     vertical-align: text-top;">
                    <h5 ><u>Notes & Remark</u></h5><br>
                   <h6 > <span class="normal_text">{{ $bill->remark }}</span></h6>
                </td>
                <td style="width: 25%;    vertical-align: text-top;">

                   <h5>Bank Details</h5>
                    <h6>Bank Name : 
                            <span class="normal_text">{{ $bill_party->bankname }}</span>
                       
                    </h6>
                    <h6>A/C No. : 
                            <span class="normal_text">{{ $bill_party->bank_ac }}</span>
                        
                    </h6>
                    <h6>IFSC Code : 
                            <span class="normal_text">{{ $bill_party->ifsc }}</span>
                     
                    </h6>
                    <h6>A/C Holder Name : 
                        <span class="normal_text">{{ $bill_party->ac_holder_name }}</span>
                 
                </h6>
                 

                </td>
                <td style="width:25%;    vertical-align: text-top;">
                    <h5>
                        Status : <span class="normal_text">{{$bill->status}}</span></h5>
                        <br>
                    @if ($bill->status == 'Approved')
                        <h4> <img src="{{ url('/images/approved.jpg') }}" height="100px" width="100px" /></h4>
                    @endif

                    @if ($bill->status == 'Paid')
                        <h4> <img src="{{ url('/images/paid.png') }}" height="100px" width="100px" /></h4>
                    @endif

                    @if ($bill->status == 'Pending')
                        <h4> <img src="{{ url('/images/pending.jpg') }}" height="100px" width="100px" /></h4>
                    @endif

                    @if ($bill->status == 'Rejected')
                        <h4> <img src="{{ url('/images/rejected.png') }}" height="100px" width="100px" /></h4>
                    @endif
                                  </td> 
                <td style="width:25%;    vertical-align: bottom;">
                    <h5>Grand Total :  {{ getStructuredAmount($bill->amount, false, false) }}</h5>
                    <br>
                    <h5>Party Balance :  {{ getStructuredAmount($balance, false, false) }}</h5>
                 <br><br>
                    <small style="font-size:10px;">This Is A Computer Generated PDF. It Does Not Require Physical
                        Signature.</small>
                </td>
            
            </tr>
        </table>
        <br>
    </div>

    <div class="hmain">
        <br>
        <h6 style="text-align:right; margin-right:5%">Bill PDF Generated By <u><a
                    href="https://constructionmunshi.com/" target="_blank" style="color:white;">Construction
                    Munshi</a></u></h6>

    </div>

</body>
</html>
