<html>

<head>
    <style>
        .sub {
            display: flex;
            /* align-items: center; */
            justify-content: space-between;
            color: white;
            place-content:space-between;
        }
        .half-div1{margin-left:20px; margin-right:20px;width: 35%; display: inline-block; vertical-align: top;}

        .half-div2{margin-left:20px; margin-right:20px;width: 45%; display: inline-block; vertical-align: top;}


        h4,h6 {
            margin: 0;
        }

        .row {
            display: flex;
            justify-content: space-between;
            border-bottom: 1px solid #ccc;
            padding: 8px 0;
        }

        .header {
            font-weight: bold;
        }




        #customers {
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 100%;
            padding-bottom: 30px;
            
        }

        #customers td,
        #customers th {
            border: 1.5px solid black;
            font-size: 6px;
            padding: 8px;
        }


        #customers th {

            padding-top: 12px;
            padding-bottom: 12px;
            text-align: center;
           
            color: white;
        }

        .tmain {
            background-color: white;
            margin: 10px;
           
            padding: 2px;
            border-radius: 25px;
        }

        .hmain {
            color: white;
            font-size: 25px;
            margin-top: -20px;
        }

        h3 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        hr {
            height: 1.5px;
            width: 90%;
            background-color: black;
            margin-bottom: 30px;

        }
    </style>
</head>

<body style="background-color:{{ $primary_color ?? session()->get('primary_color')[0] ?? '#34495e' }}; border-radius: 25px;">


  
    <div class="hmain">
        <h3 style="font-size:40px;">Site Statement</h3>

        <p style="margin-top:-30px;">Site Name : {{ $site_name }}</p>
         
        <div class="sub">
        <div class="half-div1" style="float:left;">
            <h6>Report Generated From </h6> <h4><u><a href="https://constructionmunshi.com/" target="_blank" style="color:white;">Build Arya</a></u></h4>

        </div>
        <div class="half-div2" style="float:right;">
            <h6>Report Generated On: <?= date('d-m-Y') ?> </h6>
            <h6>Report Generated By: {{ $generator_name ?? session('name') ?? 'System' }} </h6>
            <h6>Report Period: {{$start_date}} To {{$end_date}} </h6>
        </div>

      </div>
      <br>
      <br>
    </div>
    </div>
    <div class="tmain">
        <h3 style="font-size:30px;">{{ $comp_name ?? session('comp_name') ?? 'N/A' }}</h3>
        <h3 style="font-size:15px;margin-top:-25px;">Address: {{ $comp_add ?? session('comp_add') ?? 'N/A' }}</h3>
        <p style="font-size:15px;">Mobile: {{ $comp_mobile ?? session('comp_mobile') ?? 'N/A' }} &#160;&#160; Email: {{ $comp_email ?? session('comp_email') ?? 'N/A' }}</p>
        <hr>
        <table id="customers">
            <thead>
                <tr>


                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">#</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Date</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Ref</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Ref No.</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">User</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Site</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Credit</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Debit</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Particular</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Image</th>
                    <th style="background-color:{{ $secondry_color ?? session()->get('secondry_color')[0] ?? '#2c3e50' }};">Balance</th>
                    

                </tr>
            </thead>
            <tbody>
                @php $count =0;@endphp
                @if(count($filteredData)>0)
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td ></td>
                  
                    <td colspan="3" style="font-weight:bold;" >Site Opening Balance</td>

                        
                    <td colspan="3" style="font-weight:bold;" >{{$openingBalance}}</td>
                </tr>
                @php
                $currentBalance = $openingBalance;
                $total_credit = 0;
                $total_debit=0;
                @endphp
                @foreach($filteredData as $dat)
              
                <tr>
                    <td>{{ ++$count }}</td>
                    <td style="font-weight:bold;" >{{ $dat['date'] }}</td>
                    <td>{{ $dat['ref'] }}</td>
                    <td>{{ $dat['ref_no'] }}</td>
                    <td>{{ $dat['user_name'] }}</td>
                    <td>{{ $dat['site_name'] }}</td>
                    @php
                    $currentBalance = floatval($currentBalance) + floatval($dat['credit']) - floatval($dat['debit']);
                    $total_credit += floatval($dat['credit']);
                    $total_debit += floatval($dat['debit']);
                    @endphp
                    <td  style="font-weight:bold;" >{{ $dat['credit'] }}</td>
                    <td  style="font-weight:bold;" >{{ $dat['debit'] }}</td>
                    <td>{{ $dat['particular'] }}</td>
                    <td>
                        @if($dat['image'] != '' && $dat['image'] != null && $dat['image'] != 'images/expense.png')
                        <a href="<?= attachmentUrl($dat['image']) ?>">View Image</a>
                 
                        @endif
                    </td>
                    <td  style="font-weight:bold;" >{{ round($currentBalance,2) }}</td>
               
                </tr>
                @endforeach
                <tr>
                    <td></td>
                    <td style="font-weight:bold;" ></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td style="font-weight:bold;">Total</td>
                    <td  style="font-weight:bold;" >{{ round($total_credit,2) }}</td>
                    <td  style="font-weight:bold;" >{{ round($total_debit,2) }}</td>
                  
                    <td colspan="2" style="font-weight:bold;">Closing Balance</td>
                    <td  style="font-weight:bold;" >{{ round($currentBalance,2) }}</td>
               
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td ></td>
                  
                    <td colspan="3" style="font-weight:bold;">Site Current Balance</td>

                        
                    <td colspan="3" style="font-weight:bold;" >{{$sitebalance}}</td>
                </tr>
                @else
                <tr>
                <td colspan="3">No Transaction Found</td>
                
                </tr>
                @endif
            </tbody>

        </table>
      
    </div>

    </div>  

</body>

</html>