<table>
    <tr>
        <td colspan="11" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:20px; font-weight:bold;" colspan="5"
            rowspan="1">
            Bill Report
            <br>
            Report Period : {{ $start_date }} - {{ $end_date }}
          

        </td>
        <td style="background-color: {{$color}}; color:white;"colspan="1" rowspan="1">

        </td>
        <td style="background-color: {{$color}}; color:white; padding-top:10px;" colspan="5" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
            

        </td>


    </tr>


    <tr>
        <td colspan="11" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:17px; font-weight:bold;" colspan="11"
            rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="11" rowspan="1">
            <b> Address : </b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="11" rowspan="1">
            <b> Mobile : </b> <?= session('comp_mobile') ?> | <b>E-mail : </b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="11" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Date</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Bill No.</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Bill Period</th>

        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Party Name</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Site</th>

        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">User</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Location</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Remark</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Amount</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Status</th>
    </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($bills as $bill)
        <tr>
            <td rowspan="{{count($bill->items)+2}}" >{{ ++$count }}</td>
            <td  style="font-weight:bold;"  rowspan="{{count($bill->items)+2}}" >{{ $bill->billdate }}</td>
            
            <td  style="font-weight:bold;"  rowspan="{{count($bill->items)+2}}" >{{ $bill->bill_no }}</td>
            <td >{{ $bill->bill_period }}</td>
            
            <td>{{ $bill->party_name }}</td>
            <td>{{ $bill->site_name }}</td>

            <td>{{ $bill->user_name }}</td>
        
            <td>{{ $bill->location }}</td>
            <td>{{ $bill->remark }}</td>
            <td rowspan="{{count($bill->items)+2}}" style="font-weight:bold;" >{{ $bill->amount }}</td>
            @if ($bill->status == 'Pending')
                <td rowspan="{{count($bill->items)+2}}"  style="color:orange;">{{ $bill->status }}</td>
            @elseif($bill->status == 'Rejected')
                <td rowspan="{{count($bill->items)+2}}"  style="color:red;">{{ $bill->status }}</td>
            @else
                <td rowspan="{{count($bill->items)+2}}"  style="color:green;">{{ $bill->status }}</td>
            @endif
         
        </tr>
        @php
        $count2 = 1;
    @endphp
    @if (count($bill->items) > 0)
        <tr>
         
            <th style="border:2px solid {{ $color }}; color:black;">#
            </th>
            <th style="border:2px solid {{ $color }}; color:black;">
                Work</th>
            <th style="border:2px solid {{ $color }}; color:black;">
                Unit</th>
            <th style="border:2px solid {{ $color }}; color:black;">
                Rate</th>
            <th style="border:2px solid {{ $color }}; color:black;">QTY
            </th>
            <th style="border:2px solid {{ $color }}; color:black;">
                Amount</th>


          
        </tr>

        @foreach ($bill->items as $item)
            <tr>
               
                <td
                    style="border:2px solid {{ $color }};     text-align: center;">
                    {{ $count2++ }}</td>

                <td
                    style="border:2px solid {{ $color }};     text-align: center;">
                    {{ $item->work_name }}</td>
                <td
                    style="border:2px solid {{ $color }};     text-align: center;">
                    {{ $item->unit }}</td>

                <td
                    style="border:2px solid {{ $color }};     text-align: center;">
                    {{ $item->rate }}</td>
                <td
                    style="border:2px solid {{ $color }};     text-align: center;">
                    {{ $item->qty }}</td>
                <td
                    style="border:2px solid {{ $color }}; font-weight:bold;     text-align: center;">
                    {{ $item->amount }}</td>

              
            </tr>
        @endforeach
        <tr>
            <th style="border:none;"></th>
            <th style="border:none;"></th>


            <th style="border:none;"></th>
            <th style="border:none;"></th>
            <th style="border:none;"></th>
            <th style="border:none;"></th>
            <th style="border:none;"></th>

            <th style="border:none;"></th>
            <th style="border:none;"></th>
            <th style="border:none;"></th>
            <th style="border:none;"></th>

        </tr>
    @endif
    @endforeach
</table>
