<table>
    <tr>
        <td colspan="12" rowspan="1" style="background-color: orange;"></td>
    </tr>
    <tr>
        <td style="background-color: orange;  color:white; font-size:20px; font-weight:bold;" colspan="5"
            rowspan="1">
            Site Bill Report

        </td>
        <td style="background-color: orange; color:white;"colspan="2" rowspan="1">

        </td>
        <td style="background-color: orange; color:white; " colspan="5" rowspan="1">
            Report Generated At : 21/Dec/2023<br>
            Report Generated By : Manvendra Singh

        </td>


    </tr>

    <tr>

        <td style="background-color: orange;  color:white;" colspan="5" rowspan="1">
            Report Period : {{ $start_date }} - {{ $end_date }}
        </td>

        <td style="background-color: orange; color:white;"colspan="2" rowspan="1">

        </td>
        <td style="background-color: orange; color:white; font-weight:bold; " colspan="5" rowspan="1">
            Report Generated By BuildArya
        </td>

    </tr>
    <tr>
        <td colspan="12" rowspan="1" style="background-color: orange;"></td>
    </tr>
    <tr>
        <td style="background-color: orange;  color:white; font-size:17px; font-weight:bold;" colspan="12"
            rowspan="1">
            R. S. Geo. Tech India Pvt. Ltd.
        </td>
    </tr>
    <tr>
        <td style="background-color: orange;  color:white;" colspan="12" rowspan="1">
            Address : C-20, Sector 23, Sanjay Nagar, Raj Nagar, Ghaziabad, UP , IN , 201002
        </td>
    </tr>
    <tr>
        <td style="background-color: orange;  color:white;" colspan="12" rowspan="1">
            Mobile : +91 9560711138 E-mail : contact@kashpark.com
        </td>
    </tr>
    <tr>
        <td colspan="12" rowspan="1" style="background-color: orange;"></td>
    </tr>
    <tr>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Name</th>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Head Name</th>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Site Name</th>
        {{-- <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Particular</th> --}}
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Cost Price</th>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Sale Price</th>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Expenses</th>
        <th style="background-color: #05c8d6; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Status</th>
    </tr>
    @php
        $count = 0;
    @endphp
    @foreach ($Expenses as $exp)
        <tr>
            <td>{{ ++$count }}</td>
            <td>{{ $exp->name }}</td>
            <td>{{ $exp->head_id }}</td>
            <td>{{ $exp->site_id }}</td>
            {{-- <td>{{ $exp->particular }}</td> --}}
            <td>{{ $exp->cost_price }}</td>
            <td>{{ $exp->sale_price }}</td>
            <td>{{ $exp->expense_id }}</td>
            
            @if ($exp->status == 'Working')
                <td style="color:orange;">{{ $exp->status }}</td>
            @elseif($exp->status == 'Rejected')
                <td style="color:red;">{{ $exp->status }}</td>
            @else
                <td style="color:green;">{{ $exp->status }}</td>
            @endif
            {{-- <td><a href="https://console.constructionmunshi.com/{{ $exp->image }}">View Image</a></td> --}}

        </tr>
    @endforeach
</table>
