<table>
    <tr>
        <td colspan="17" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:20px; font-weight:bold;" colspan="17"
            rowspan="1">
            Material Report
          

        </td>
       </tr>

        <tr>
            <td style="background-color: {{$color}};  color:white; font-size:18px; font-weight:bold;" colspan="9"
            rowspan="1">
            <br>
            Head Name - <?= $headname?>
            <br>
            Site Name - <?= $sitename?>

            

        </td>
        <td style="background-color: {{$color}}; color:white; padding-top:10px;" colspan="8" rowspan="1">
            <b> Report Generated By Build Arya
            </b><br>
            Report Generated At : <?= date('d-m-Y') ?><br>
            Report Generated By : <?= session('name') ?><br>
            Report Period : {{ $start_date }} - {{ $end_date }}

        </td>


    </tr>


    <tr>
        <td colspan="17" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white; font-size:17px; font-weight:bold;" colspan="17"
            rowspan="1">
            <?= session('comp_name') ?>

        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="17" rowspan="1">
            <b> Address :</b> <?= session('comp_add') ?>
        </td>
    </tr>
    <tr>
        <td style="background-color: {{$color}};  color:white;" colspan="17" rowspan="1">
            <b> Mobile :</b> <?= session('comp_mobile') ?> | <b>E-mail :</b> <?= session('comp_email') ?>
        </td>
    </tr>
    <tr>
        <td colspan="17" rowspan="1" style="background-color: {{$color}};"></td>
    </tr>
    <tr>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">
            #
        </th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Date</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Supplier</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Is Royalty</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Unit</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Qty</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Vehicle</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Bill No.</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Rate</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Tax</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Amount</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">User</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Location</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Remark</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Status</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Image</th>
        <th style="background-color: {{$sec_color}}; color:white; font-weight:bold;  border:1px solid #e3e3e3;">Image</th>
    </tr>
    @php
        $count = 1;
    @endphp
    @foreach ($material as $mat)
    <tr>
        <td>{{ $count++ }}</td>
        <td>{{ $mat->date }}</td>
        <td>{{ $mat->supplier }}</td>
        <td>{{ ($mat->is_royalty) ? 'Yes' : 'No' }}</td>
        <td>{{ $mat->unit }}</td>
        <td>{{ $mat->qty }}</td>
        <td>{{ $mat->vehical }}</td>
        <td>{{ $mat->bill_no }}</td>
        <td>{{ $mat->rate }}</td>
        <td>{{ $mat->tax }}</td>

        <td  style="font-weight:bold;">{{ $mat->amount }}</td>

        <td>{{ $mat->user }}</td>


        <td>{{ $mat->location }}</td>
        <td>{{ $mat->remark }}</td>

        @if ($mat->status == 'Pending')
            <td style="color:orange;">{{ $mat->status }}</td>
        @elseif($mat->status == 'Rejected')
            <td style="color:red;">{{ $mat->status }}</td>
        @else
            <td style="color:green;">{{ $mat->status }}</td>
        @endif

        @if ($mat->image != 'images/expense.png' && $mat->image != null)
            <td>
                <a href="<?= attachmentUrl($mat->image) ?>">View Image</a>
            </td>
        @else
            <td></td>
        @endif
        @if ($mat->image2 != 'images/expense.png' && $mat->image2 != null)
            <td>
                <a href="<?= attachmentUrl($mat->image2) ?>">View Image</a>
            </td>
        @else
            <td></td>
        @endif

    </tr>
@endforeach
</table>
